<!-- intouch.txt -->
       <div id="notice">
       <hr noshade>
       <li>Image used by permission of
       Anthony King.
       <li>&ldquo;Altered Default
       Mode Network (DMN) Resting State Functional
       Connectivity Following a Mindfulness-Based
       Exposure Therapy for Posttraumatic Stress
       Disorder (PTSD) in Combat Veterans of
       Afghanistan and Iraq&rdquo;, Anthony P. King,
       Stefanie R. Block, Rebecca K. Sripada, et al.
       <em>Depression and Anxiety</em>, 33: 289–299.
       <a href="http://onlinelibrary.wiley.com/doi/10.1002/da.22481/abstract">doi:10.1002/da.22481</a></li>
       <hr noshade>
       </div>
