<!-- Begin menu.inc -->
    <li class="subtitle">Topics</li>
    <li><hr noshade></li>
    <li class="subtitle"><a href="http://www.umich.edu/~nii/index.html">&ndash; About</a></li>
    <li class="subtitle"><a href="http://www.umich.edu/~nii/people.html">&ndash; People</a></li>
    <li class="subtitle"><a href="http://www.umich.edu/~nii/communicating.html">&ndash; Communicating</a></li>
    <li class="subtitle"><a href="http://www.umich.edu/~nii/consulting.html">&ndash; Consulting</a></li>
    <li class="subtitle"><a href="http://www.umich.edu/~nii/events.html">&ndash; Events</a></li>
    <li class="subtitle"><a href="http://private.www.umich.edu/~nii/journal.html">&ndash; Journal Club</a></li>
<!--
    <li class="subtitle"><a href="http://www.umich.edu/~nii/publications.html">&ndash; Publications</a></li>
-->
    <li class="subtitle">Computing</li>
       <li>&emsp;&ndash; <a href="http://www.umich.edu/~nii/brainbox.html">YBRC Brainbox</a></li>
       <li>&emsp;&ndash; <a href="http://www.umich.edu/~nii/flux.html">Flux</a></li>
       <li>&emsp;&ndash; <a href="http://www.umich.edu/~nii/xsede.html">XSEDE</a></li>
       <li>&emsp;&ndash; <a href="http://www.umich.edu/~nii/tutorial.html">Tutorials and training</a></li>
<!--
    <p>&nbsp;</p>
    <li class="subtitle">Private pages</li>
    <hr noshade>
    <li class="subtitle"><a href="https://private.www.umich.edu/~nii/software.html">&ndash; Software</a></li>
    <hr noshade>
    <p>&nbsp;</p>
-->
<!-- End menu.inc -->
