
<h3>Analysis packages: Origins and overviews</h3>
<hr noshade>

<p>AFNI: What a long strange trip it's been,
<br>Robert W. Cox,
<br><em>NeuroImage</em> 62 (2012) 743-747

<p>Brain templates and atlases,
<br>Alan C. Evans, et al.,
<br><em>NeuroImage</em> 62 (2012) 911-922

<p>BrainVoyager &mdash; Past, present, future,
<br>Rainer Goebel,
<br><em>NeuroImage</em> 62 (2012) 748-756

<p>Cortical cartography and Caret Software,
<br>David C. Van Essen
<br><em>NeuroImage</em> 62 (2012) 757-764

<p>FreeSurfer,
<br>Bruce Fischl
<br><em>NeuroImage</em> 62 (2012) 774-781

<p>FSL,
<br>Mark Jenkinson, et al.,
<br><em>NeuroImage</em> 62 (2012) 782-790

<p>Motivation and Synthesis of the FIAC Experiment: Reproducibility of fMRI
Results Across Expert Analyses,
<br>Jean Baptiste Poline, et al.,
<br><em>Human Brain Mapping</em>, 27:351-359 (2006)

<p>SPM: A history,
<br>John Ashburner,
<br><em>NeuroImage</em> 62 (2012) 791-800

<h3>Connectivity</h3>
<hr noshade>

<p>The effect of scan length on the reliability of resting-state fMRI connectivity estimates,
<br>Rasmus M. Birn, et al.,
<br><em>NeuroImage</em> 83 (2013) 550-558

<p>Approaches for the Integrated Analysis of Structure, Function and
Connectivity of the Human Brain,
<br>Simon B. Eickhoff and Christian Grefkes,
<br><em>Clinical EEG and Neuroscience</em>, Copyright 2011 VOL. 42 NO. 2

<p>Functional and Effective Connectivity: A Review,
<br>Karl J. Friston,
<br><em>Brain Connectivity</em> Volume 1, Number 1, 2011

<p>Imaging structural and functional connectivity: towards a unified definition of human brain organization?
<br>Maxime Guye, et al.,
<br><em>Current Opinion in Neurology</em> 2008, 21:393-403

<p>MATLAB toolbox for functional connectivity,
<br>Dongli Zhou, Wesley K. Thompson, Greg Siegle,
<br><em>NeuroImage</em> 47 (2009) 1590-1607

<p>Test-retest reliabilities of resting-state FMRI measurements in human brain functional connectomics: A systems neuroscience perspective,
<br>Xi-Nian Zuoa, Xiu-Xia Xing,
<br><em>Neuroscience and Biobehavioral Reviews</em> 45 (2014) 100-118

<h3>Default mode overview</h3>
<hr noshade>

<p>Functional-Anatomic Fractionation of the Brain's Default Network,
<br>Jessica R. Andrews-Hanna,
<br><em>Neuron</em> 65, 550-562, February 25, 2010

<p>The Brain's Default Network Anatomy, Function, and Relevance to Disease,
<br>Randy L. Buckner, Jessica R. Andrews-Hanna, Daniel L. Schacter,
<br><em>Ann. N.Y. Acad. Sci.</em> 1124: 1-38 (2008)

<h3>Design issues</h3>
<hr noshade>

<p>Study design in fMRI: Basic principles,
<br>Edson Amaro, Jr., Gareth J. Barker,
<br><em>Brain and Cognition</em> 60 (2006) 220-232

<p>A history of randomized task designs in fMRI,
<br>Vincent P. Clark,
<br><em>NeuroImage</em> 62 (2012) 1190-1194

Development of orthogonal task designs in fMRI studies of higher cognition: The NIMH experience,
<br>Susan M. Courtney,
<br><em>NeuroImage</em> 62 (2012) 1185-1189

<p>The development and use of phase-encoded functional MRI designs,
<br>Stephen A. Engel,
<br><em>NeuroImage</em> 62 (2012) 1195-1200

<p>The development of event-related fMRI designs,
<br>Thomas T. Liu,
<br><em>NeuroImage</em> 62 (2012) 1157-1162

<p>Studying the freely-behaving brain with fMRI,
<br>Eleanor A. Maguire,
<br><em>NeuroImage</em> 62 (2012) 1170-1176

<p>Targeting the functional properties of cortical neurons using fMR-adaptation,
<br>Rafael Malach,
<br><em>NeuroImage</em> 62 (2012) 1163-1169

<p>The mixed block/event-related design,
<br>Steven E. Petersen, Joseph W. Dubis
<br><em>NeuroImage</em> 62 (2012) 1177-1184

<p>Optimization of experimental design in fMRI: a general framework using a
genetic algorithm,
<br>Tor D. Wager and Thomas Nichols,
<br><em>NeuroImage</em> 18 (2003) 293-309

<h3>Dynamic Connectivity</h3>

<p>The Chronnectome: Time-Varying Connectivity Networks as the Next
Frontier in fMRI Data Discovery,
<br>Vince D. Calhoun, Robyn Miller, et al.
<br><em>Neuron</em>, Volume 84, Issue 2, p262–274, 22 October 2014
<br>http://dx.doi.org/10.1016/j.neuron.2014.10.015

<p>Dynamic functional connectivity: Promise, issues, and interpretations.
<br>R. Matthew Hutchison, Thilo Womelsdorf, et al.,
<br><em>NeuroImage</em> 80 (2013) 360- 378
<br>http://dx.doi.org/10.1016/j.neuroimage.2013.05.079

<p>Functional interactions between intrinsic brain activity and behavior,
<br>Sepideh Sadaghiani, Andreas Kleinschmidt,
<br><em>Neuroimage</em> 80 (2013) 379-386<br>
<br>http://dx.doi.org/10.1016/j.neuroimage.2013.04.100

<p>
<br>
<br>
<br>

